name: Nofelet-backend pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  APP_NAME: ${{ vars.APP_NAME }}
  APP_PATH: ${{ vars.APP_PATH }}
  BINARY_NAME: ${{ vars.BINARY_NAME }}

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Run tests
        run: |
          go test ./... -v
        continue-on-error: true  # Пока тесты не обязательны

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Build Linux binary
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=amd64 go build --ldflags="-s -w" -v -o bin/$BINARY_NAME cmd/signaling/main.go

      - name: Show binary info
        run: |
          ls -la bin/
          file bin/$BINARY_NAME

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-binary
          path: bin/
          retention-days: 2

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-binary
          path: bin/

      - name: Debug - посмотреть что скачалось
        run: |
          echo "Текущая директория: $(pwd)"
          echo "Содержимое bin/:"
          ls -la bin/
          echo "Полный путь к бинарнику:"
          find . -name "${{ vars.BINARY_NAME }}" -type f

      - name: Fix binary permissions
        run: |
          chmod +x bin/${{ vars.BINARY_NAME }}
          ls -la bin/${{ vars.BINARY_NAME }}  # Проверим права

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            mkdir -p ${{ env.APP_PATH }}/{bin,logs,config}
            cp bin/${{ env.BINARY_NAME }} ${{ env.APP_PATH }}/bin/
            chmod +x ${{ env.APP_PATH }}/bin/${{ env.BINARY_NAME }}